'use strict';

module.exports = {

  up(db, next) {
    var persons=db.collection('persons');
    persons.insertMany([
      {id:0,image:"/images/download.jpg",name:"Tylor Swift",overview:"After an 5-year technical career working with  most well-respected startups. She enjoys freelancing because it provides her the opportunity to meet so many fascinating entrepreneurs, investors, and lenders and allows her to leverage her experiences to help them maximize value from the mountains.",currentwork:"UI developer",degree1:"M.Tech",degree2:"B.Tech",linkedinurl:"https://www.linkedin.com/in/tejaswi-chava-336a8a122/",twitterurl:"https://www.linkedin.com/in/tejaswi-chava-336a8a122/",emailid:"tylor.swift@gmail.com",joinedon:"22/06/2000",passedon:"22/12/2000",salary:200000,hidesalary:false,country:"Telangana,India",technicalskills:"JAVA,Java Script,HTML,CSS",previouswork:"Meanstack Developer",degree1description:"M.Tech in Computer Science",degree2description:"B.Tech in Computer Science",
      employment:"Contributed software engineering expertise in the development of products through the software lifecycle, from requirements definition through successful deployment Facilitated customization of systems by encouraging software engineering team to adopt emerging standards for software application development architecture and tools.Participated in sales presentations due to ability to translate user needs into easy-to-understand software solutions. Helped sales team close five major deals generating more than $150K in revenue.Excelled in rapid application development and management of technological issues for assigned projects, earning the highest customer satisfaction rating for all software solutions delivered.Introduced methodologies and best practices that enhanced product definition, release processes and customization of applications to user needs.",
      employment2:"Assisted in the design and development of user information solutions and Internet applications for a leading financial services company. Provided user requirements analysis, design and programming support for enhancement of Web application accessed by 5 million users worldwide.Fueled additional revenue stream through responsive customer support, generating $18K in new license sales within first few weeks of new product release.",
      tags:[{name:"Adobe Photoshop"},{name:"User Interface"},{name:"User Experience"}]
    },
      {id:1,image:"/images/miximac.jpg",name:"Mixi Mac",overview:"After an 6-year technical career working with  most well-respected startups. She enjoys freelancing because it provides her the opportunity to meet so many fascinating entrepreneurs, investors, and lenders and allows her to leverage her experiences to help them maximize value from the mountains.",currentwork:"Java developer",degree1:"M.Tech",degree2:"B.Tech",linkedinurl:"https://www.linkedin.com/in/tejaswi-chava-336a8a122/",twitterurl:"https://www.linkedin.com/in/tejaswi-chava-336a8a122/",emailid:"tylor.swift@gmail.com",joinedon:"22/06/2000",passedon:"22/12/2000",salary:300000,hidesalary:false,country:"Andhrapradesh,India",technicalskills:"JAVA,Java Script,HTML,CSS",previouswork:"Meanstack Developer",degree1description:"M.Tech in Computer Science",degree2description:"B.Tech in Computer Science",employment:"Contributed software engineering expertise in the development of products through the software lifecycle, from requirements definition through successful deployment Facilitated customization of systems by encouraging software engineering team to adopt emerging standards for software application development architecture and tools.Participated in sales presentations due to ability to translate user needs into easy-to-understand software solutions. Helped sales team close five major deals generating more than $150K in revenue.Excelled in rapid application development and management of technological issues for assigned projects, earning the highest customer satisfaction rating for all software solutions delivered.Introduced methodologies and best practices that enhanced product definition, release processes and customization of applications to user needs.",
      employment2:"Assisted in the design and development of user information solutions and Internet applications for a leading financial services company. Provided user requirements analysis, design and programming support for enhancement of Web application accessed by 5 million users worldwide.Fueled additional revenue stream through responsive customer support, generating $18K in new license sales within first few weeks of new product release."},
      {id:2,image:"/images/acejane.jpg",name:"Ace Jane",overview:"After an 5-year technical career working with  most well-respected startups. She enjoys freelancing because it provides her the opportunity to meet so many fascinating entrepreneurs, investors, and lenders and allows her to leverage her experiences to help them maximize value from the mountains.",currentwork:"UI developer",degree1:"M.Tech",degree2:"B.Tech",linkedinurl:"https://www.linkedin.com/in/tejaswi-chava-336a8a122/",twitterurl:"https://www.linkedin.com/in/tejaswi-chava-336a8a122/",emailid:"tylor.swift@gmail.com",joinedon:"22/06/2000",passedon:"22/12/2000",salary:400000,hidesalary:false,country:"Karnataka,India",technicalskills:"JAVA,JavaScript,HTML,CSS",previouswork:"Meanstack Developer",degree1description:"M.Tech in Computer Science",degree2description:"B.Tech in Computer Science",employment:"Contributed software engineering expertise in the development of products through the software lifecycle, from requirements definition through successful deployment Facilitated customization of systems by encouraging software engineering team to adopt emerging standards for software application development architecture and tools.Participated in sales presentations due to ability to translate user needs into easy-to-understand software solutions. Helped sales team close five major deals generating more than $150K in revenue.Excelled in rapid application development and management of technological issues for assigned projects, earning the highest customer satisfaction rating for all software solutions delivered.Introduced methodologies and best practices that enhanced product definition, release processes and customization of applications to user needs.",
      employment2:"Assisted in the design and development of user information solutions and Internet applications for a leading financial services company. Provided user requirements analysis, design and programming support for enhancement of Web application accessed by 5 million users worldwide.Fueled additional revenue stream through responsive customer support, generating $18K in new license sales within first few weeks of new product release."},
      {id:3,image:"/images/philipjames.jpg",name:"Philip James",overview:"After an 5-year technical career working with  most well-respected startups. She enjoys freelancing because it provides her the opportunity to meet so many fascinating entrepreneurs, investors, and lenders and allows her to leverage her experiences to help them maximize value from the mountains.",currentwork:"UI developer",degree1:"M.Tech",degree2:"B.Tech",linkedinurl:"https://www.linkedin.com/in/tejaswi-chava-336a8a122/",twitterurl:"https://www.linkedin.com/in/tejaswi-chava-336a8a122/",emailid:"tylor.swift@gmail.com",joinedon:"22/06/2000",passedon:"22/12/2000",salary:500000,hidesalary:false,country:"Tamilnadu,India",technicalskills:"JAVA,JavaScript,HTML,CSS",previouswork:"Meanstack Developer",degree1description:"M.Tech in Computer Science",degree2description:"B.Tech in Computer Science",employment:"Contributed software engineering expertise in the development of products through the software lifecycle, from requirements definition through successful deployment Facilitated customization of systems by encouraging software engineering team to adopt emerging standards for software application development architecture and tools.Participated in sales presentations due to ability to translate user needs into easy-to-understand software solutions. Helped sales team close five major deals generating more than $150K in revenue.Excelled in rapid application development and management of technological issues for assigned projects, earning the highest customer satisfaction rating for all software solutions delivered.Introduced methodologies and best practices that enhanced product definition, release processes and customization of applications to user needs.",
      employment2:"Assisted in the design and development of user information solutions and Internet applications for a leading financial services company. Provided user requirements analysis, design and programming support for enhancement of Web application accessed by 5 million users worldwide.Fueled additional revenue stream through responsive customer support, generating $18K in new license sales within first few weeks of new product release."}
    ],next);
    next();
  },

  down(db, next) {
    // TODO write the statements to rollback your migration (if possible)
    next();
  }

};